# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d47115b5157c202bad50e40c7f0b51afd2640a5af065e5f17000947ee72bcae87a8f6d24e7dc2bb1a7317d0c54eb21b48e8db36334cee92825802a2f305985f

test:
  secret_key_base: c938f11e8099226fa853e9684c253ef64adfc6c6eb0499ad88d54c78d73d3f1cb07af7e8b1098c93c2ce47758eda07ca797a2866ea4c00eef1270fdde92e82c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
